### ISSUE TITLE
Failed test status not being sent

### ISSUE THREAD

**Issue by shineqwe** [alexmorez/codeceptjs-testit-reporter#1]
Hello.
I have connected your adapter. But the failed test status is not passed to testit. Only successful tests are sent (

**Comment by alexmorez** [comment]
@shineqwe, Hi. Tests run results in Test IT must be connected with tests entities. Test entity creates only when test passed, so failed tests results would be sent after first success run. If test never passed before, test run result will be ignored (such tests results ids are mentioned in console).

Or you have some different issue?

**Comment by shineqwe** [comment]
I found two problems, maybe they are related to my settings...

1.
- Run test

Autotest created - ok

2.
- Associated autotest with test case
- Run the test again

A new autotest has been created - although a new one should not be created - not ok

3.
1. Launched the test - an autotest was created
2. Associated the autotest with the test case
3. Run the same crash test again

An empty test-run was created - not ok

Apparently the problem occurs due to the fact that each time a new autotest is created

**Comment by alexmorez** [comment]
@shineqwe Hm, adapter initiating new test entity if it's ID is not exists in TestIT. Tests IDs in codeceptjs based on tests names. Maybe your tests names are unique for each test run?

**upd:** What version of codeceptjs do you have? I noticed some breaking changes of tests IDs generation in last **minor** version of codeceptjs

**Comment by shineqwe** [comment]
codeceptjs@3.4.1
Previous launches performed on one test

**Comment by alexmorez** [comment]
@shineqwe, I have tested plugin with newer version of codeceptjs and reproduced that behaviour with new test entity for each run, it was because of [this](https://github.com/codeceptjs/CodeceptJS/pull/3584/files#diff-0f96dc9ccfc67d83b6538f490ef3a86cc221d4fac76d33e139d56cc5d7039428L50). Fixed it in 0.3.0.

As for _"An empty test-run was created - not ok"_ - I think, that it is expected behaviour. When we creating test run, we dont't know, how many tests will passed. Empty finished test run with some duration in TestIT dashboard just hints that something went wrong.
